import type { ShowSkill } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// Licensed Google Cloud Gemini TTS Prebuilt Voices
// ─────────────────────────────────────────────────────────────────────────────

export const LICENSED_GEMINI_TTS_VOICES = [
  "Charon",
  "Orus",
  "Puck",
  "Fenrir",
  "Aoede",
  "Kore",
  "Enceladus",
] as const;

export type GeminiTtsVoice = typeof LICENSED_GEMINI_TTS_VOICES[number];

export interface VoiceProfile {
  voiceId: GeminiTtsVoice;
  timbre: string;
  resonance: "Low" | "Mid-Low" | "Mid" | "Mid-High" | "High";
  genderPresentation: "Male" | "Female" | "Neutral";
  idealPersonaAlignment: string;
}

export const LICENSED_VOICE_PROFILES: Record<GeminiTtsVoice, VoiceProfile> = {
  Charon: {
    voiceId: "Charon",
    timbre: "British / Erudite, crisp consonant articulation, dry, authoritative cadence",
    resonance: "Mid-Low",
    genderPresentation: "Male",
    idealPersonaAlignment: "Investigative Satirist, Deadpan Straight-Man News Anchor",
  },
  Orus: {
    voiceId: "Orus",
    timbre: "Measured, conversational American baritone, sharp punchlines, skeptical",
    resonance: "Mid-Low",
    genderPresentation: "Male",
    idealPersonaAlignment: "Skeptical Head-Writer Monologist, Curious Podcast Host / Sounding Board",
  },
  Puck: {
    voiceId: "Puck",
    timbre: "Warm, energetic, slightly raspy, quick-witted, casual delivery",
    resonance: "Mid-High",
    genderPresentation: "Male",
    idealPersonaAlignment: "Subversive Loose-Cannon Anchor, Esoteric Polymath Guest",
  },
  Fenrir: {
    voiceId: "Fenrir",
    timbre: "Grounded, booming, earnest curiosity, primal intensity",
    resonance: "Low",
    genderPresentation: "Male",
    idealPersonaAlignment: "Speculative Explorer Podcast Host, Primal Inquirer",
  },
  Aoede: {
    voiceId: "Aoede",
    timbre: "Bright, melodic, expressive, joyful, engaging comedic timing",
    resonance: "Mid-High",
    genderPresentation: "Female",
    idealPersonaAlignment: "High-Energy Variety Monologist, Cultural Commentator",
  },
  Kore: {
    voiceId: "Kore",
    timbre: "Calm, journalistic clarity, grounded, steady broadcast pacing",
    resonance: "Mid",
    genderPresentation: "Female",
    idealPersonaAlignment: "Fact-Checking Co-Host, Deadpan Investigative Partner",
  },
  Enceladus: {
    voiceId: "Enceladus",
    timbre: "Raspy, commanding, high-voltage satirical rant delivery, philosophical outrage",
    resonance: "Mid",
    genderPresentation: "Male",
    idealPersonaAlignment: "Apocalyptic Satirical Diatribist, Scorched-Earth Social Critic",
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Voice Verification & Assertion
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Checks whether a given string is an approved licensed Gemini TTS voice.
 */
export function isLicensedGeminiVoice(voice: string): voice is GeminiTtsVoice {
  return (LICENSED_GEMINI_TTS_VOICES as readonly string[]).includes(voice);
}

/**
 * Asserts that a voice string is a valid licensed Gemini TTS voice, throwing an error otherwise.
 */
export function assertLicensedGeminiVoice(voice: string, hostName?: string): void {
  if (!isLicensedGeminiVoice(voice)) {
    const hostLabel = hostName ? ` for host "${hostName}"` : "";
    throw new Error(
      `Illegal or unlicensed TTS voice "${voice}"${hostLabel}. Only licensed Google Cloud Gemini TTS voices are permitted: ${LICENSED_GEMINI_TTS_VOICES.join(", ")}.`,
    );
  }
}

/**
 * Resolves a host's TTS voice safely, falling back to a licensed default if unmapped.
 */
export function resolveHostTtsVoice(voice?: string, fallback: GeminiTtsVoice = "Orus"): GeminiTtsVoice {
  if (voice && isLicensedGeminiVoice(voice)) {
    return voice;
  }
  return fallback;
}

// ─────────────────────────────────────────────────────────────────────────────
// Satirical Transparency & Parody Disclaimer Generator
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generates an explicit satirical parody disclaimer to attach to media outputs,
 * affirming First Amendment parody craft and licensed AI synthesis transparency.
 */
export function generateSatiricalDisclaimer(
  skillOrName: string | ShowSkill,
  topic?: string,
): string {
  const showName = typeof skillOrName === "string" ? skillOrName : skillOrName.name;
  const topicSegment = topic ? ` on "${topic}"` : "";

  return (
    `Generated by Interdimensional Cable AI Comedy Orchestrator (${showName}${topicSegment}). ` +
    `This production is an original satirical parody and comedic commentary executing dramaturgical craft and rhetorical format spines. ` +
    `Audio synthesized exclusively using licensed Google Cloud Gemini TTS voices. Not affiliated with or endorsed by any living individual or network.`
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Prompt Sanitizer & Trademark Normalizer
// ─────────────────────────────────────────────────────────────────────────────

const NETWORK_TRADEMARK_REPLACEMENTS: Array<{ regex: RegExp; replacement: string }> = [
  { regex: /\bHBO\b/gi, replacement: "premium cable broadcast" },
  { regex: /\bNBC\b/gi, replacement: "late-night television network" },
  { regex: /\bCBS\b/gi, replacement: "broadcast television studio" },
  { regex: /\bABC\b/gi, replacement: "national broadcast studio" },
  { regex: /\bComedy Central\b/gi, replacement: "satirical comedy network" },
  { regex: /\bShowtime\b/gi, replacement: "premium cable studio" },
  { regex: /\bNetflix\b/gi, replacement: "streaming television platform" },
  { regex: /\bSpotify\b/gi, replacement: "broadcast audio streaming platform" },
  { regex: /\bLast Week Tonight\b/gi, replacement: "investigative comedy deep-dive" },
  { regex: /\bA Closer Look\b/gi, replacement: "surgical satirical breakdown" },
  { regex: /\bWeekend Update\b/gi, replacement: "dual-anchor satirical news desk" },
  { regex: /\bTonight Show\b/gi, replacement: "late-night variety monologue" },
  { regex: /\bJoe Rogan Experience\b|\bJRE\b/gi, replacement: "the speculative podcast studio" },
  { regex: /\bTim Dillon Show\b/gi, replacement: "the satirical apocalyptic podcast" },
];

/**
 * Sanitizes prompt text by stripping proprietary studio/network trademarks and replacing them
 * with generic broadcast genre descriptions. Enforces dramaturgical craft focus.
 */
export function sanitizePromptForLegalSafety(prompt: string): string {
  let sanitized = prompt;

  for (const { regex, replacement } of NETWORK_TRADEMARK_REPLACEMENTS) {
    sanitized = sanitized.replace(regex, replacement);
  }

  // Remove direct biometric cloning commands
  sanitized = sanitized.replace(/\bclone the exact voice of\b/gi, "reproduce the rhetorical cadence and comedic style of");
  sanitized = sanitized.replace(/\bdeepfake\b/gi, "stylized satirical caricature");
  sanitized = sanitized.replace(/\bimpersonate identically\b/gi, "parody the dramaturgical structure of");

  return sanitized;
}

// ─────────────────────────────────────────────────────────────────────────────
// Comprehensive Skill Legal Guardrails Validator
// ─────────────────────────────────────────────────────────────────────────────

export interface GuardrailValidationResult {
  valid: boolean;
  errors: string[];
}

/**
 * Validates that a ShowSkill definition fully respects legal and identity guardrails:
 * 1. All host TTS voices are strictly from the licensed Gemini TTS pool.
 * 2. Host persona descriptions focus on rhetorical craft rather than biometric cloning.
 * 3. Visual style prompts describe broadcast caricatures rather than photorealistic deepfakes.
 */
export function validateSkillLegalGuardrails(skill: ShowSkill): GuardrailValidationResult {
  const errors: string[] = [];

  if (!skill.hosts || skill.hosts.length === 0) {
    errors.push(`Show skill "${skill.id}" must define at least one host.`);
  }

  for (const host of skill.hosts ?? []) {
    if (!isLicensedGeminiVoice(host.ttsVoice)) {
      errors.push(
        `Host "${host.name}" in skill "${skill.id}" specifies unlicensed TTS voice "${host.ttsVoice}". Must be one of: ${LICENSED_GEMINI_TTS_VOICES.join(", ")}.`,
      );
    }

    if (!host.personaCraft || host.personaCraft.length < 15) {
      errors.push(
        `Host "${host.name}" in skill "${skill.id}" must provide rich personaCraft instructions (at least 15 characters).`,
      );
    }
  }

  if (!skill.rhetoricalSpine || !skill.rhetoricalSpine.acts || skill.rhetoricalSpine.acts.length === 0) {
    errors.push(`Skill "${skill.id}" must define a valid rhetorical spine with at least one act.`);
  }

  if (skill.visualStylePrompt && /deepfake|photorealistic identical clone/i.test(skill.visualStylePrompt)) {
    errors.push(`Skill "${skill.id}" visualStylePrompt contains prohibited biometric mimicry keywords.`);
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
